### ISSUE TITLE
Connecting with OpenSea

### ISSUE THREAD

**Issue by arshadzz** [aberghammer/NFTCollectible#1]
Hello,

I want to connect with opensea, i have also watched the video, can you please explain and help,
I have added /assets/(contract_address)/ 
what is '1' ?
I have 120 tokens in another contract, how can i link / import into My opensea???

It would be a great Help,

Best wishes,
Thanks

**Comment by aberghammer** [comment]
Hi,
check out the documentation here: https://docs.opensea.io/docs/3-viewing-your-items-on-opensea

You access the tokens of your contract like that:
https://testnets.opensea.io/assets/<asset_contract_address>/<token_id>

The '1' is your first token, '2' your second token and so on. If you didn't mint a token yet, this wouldn't work. 
If you want to link your contract with opensea read here:
https://docs.opensea.io/docs/5-create-your-storefront
And click on following link to connect your contract:
https://testnets.opensea.io/get-listed/

I hope I could answer your question. 
I'm really sorry, that you had to struggle with my german video but I think it's a little bit niche to have the content in German language.

Feel free to reach out to me anytime. Wish you good luck with your project!

Have a great day,

Andreas

**Comment by arshadzz** [comment]
Dear Andreas,

Thanks a lot, Yes, I wanted to know it exactly.

It was really helpful and my problem is solved.

Have a nice weekend,

Best Wishes,

Zubair

**Comment by aberghammer** [comment]
more a question than an issue 👍
